###

GET http://localhost:3000/users


###
GET http://localhost:3000/users/4/


###

POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "nara",
  "email": "mann@gmail.com",
  "age": 23
}
###


PUT http://localhost:3000/users/5
Content-Type: application/json

{
  "name": "narayan",
  "email": "narayana@gmail.com",
  "age": 45
}

###
DELETE http://localhost:3000/users/4
